'use-strict';
const ROUTER_PATHS = {
    ROOT: '/',
    BASE: '/V3',
    TEST_API: '/test-api',
    PLUS: '/plus',
    SELF: '/self',
    LIST: '/list',
    WALLET:'/wallet',
    DETAIL:'/detail'
};module.exports.ROUTER_PATHS = ROUTER_PATHS;

const ROUTER_PARAMS = {
    USER:"/:user",
    USERID:"/:userid",
    NAMESPACE:"/:namespace",
    LEVEL:"/:level",
    RESOURCE:"/:resource",
    VERSION : "/v:version",
    ACTION : "/:action"
};exports.ROUTER_PARAMS = ROUTER_PARAMS;

exports.RET_CODE = {
    OK: 1000,
    FAILURE: 1001,
  
    DUPLICATED: 2002,
    TOKEN_EXPIRED: 2003,
    INCORRECT_CAPTCHA: 2004,
    NONEXISTENT_HANDLE: 2005,
    INCORRECT_PASSWORD: 2006,
    INVALID_EMAIL_LITERAL: 2007,
    NO_ASSOCIATED_EMAIL: 2008,
    SEND_EMAIL_TIMEOUT: 2009,
    RESELLER_SKU_BY_GAME_DUPLICATED: 2010,
    NONEXISTENT_RESELLER: 2011,
    INSUFFICIENT_MEM_TO_ALLOCATE_CONNECTION: 2012,
    MACHINE_ALREADY_CONNECTED: 2013,
    INVALID_TICKET_CONSUMPTION_TYPE: 2014,
    TICKET_CONSUMPTION_LIMIT_EXCEEDED: 2015,
    NONEXISTENT_MACHINE: 2016,
    MACHINE_NOT_ASSIGNED_TO_RESELLER: 2017,
    NONEXISTENT_WRITER: 2018,
    NONEXISTENT_ARTICLE: 2019,
    NEW_ARTICLE_LIMIT_EXCEEDED: 2020,
  
    INVALID_MACHINE_CREDENTIALS: 3000,
  
    PASSWORD_RESET_CODE_GENERATION_PER_EMAIL_TOO_FREQUENTLY: 4000,
    CAPTCHA_GENERATION_PER_PHONE_TOO_FREQUENTLY: 4001,
    PURCHASE_CREATION_TOO_FREQUENTLY: 4002,
  
    NOT_IMPLEMENTED_YET: 65535,
  };
